### ISSUE TITLE
Idée pour show_face

### ISSUE THREAD

**Issue by Lyokolux** [InfoIsfatesDfhi/Projet_Rubics-cube#1]
La fonction `show_face` ressemble à ça :
```python
def show_face(face):
    counter = 1
    row = ''
    for color in face:
        row += color + ' '
        if counter % 3 == 0:
            print(row)
            row = ''
        counter += 1
    print('\n')
```

On pourrais l'améliorer en : 
```python
def show_face(face):
    row = ''
    for (counter, color) in enumerate(face):
        row += color + ' '
        if (counter + 1) % 3 == 0:
            print(row)
            row = ''
    print()
```
La variable counter reste dans la boucle `for` et est incrémentée à chaque itération. 
Pour le `print('\n')` de la dernière ligne, l'objectif est de laisser 2 lignes ? Car il y a le celui dans le `print` et celui par défaut : `print(end='\n')`
Après c'est un détail :smiley_cat:

**Comment by Lyokolux** [comment]
Une autre idée avec un seul `print`:
```python
def show_face(face):
    row = ''
    for (counter, color) in enumerate(face):
        row += color + ' '
        if (counter + 1) % 3 == 0:
            row += '\n'
    print(row)
```
Cela sépare le traitement de l'affichage, après cela reste du détail et c'est du pinaillage.
La question est: combien de retour à la ligne après l'affichage de row ? Il y en a un dans row, avec un autre dans le `print`.

**Comment by johannchopin** [comment]
Tu as mis le doigt sur un petit problème d'affichage en effet. Le retour supplémentaire à la ligne ne devrait pas être codé dans `show_face` mais dans  `show_cube` à vrai dire. Mais je pense qu'il serait judicieux de garder ta dernière idée qui sépare le traitement de l'affichage 😉 Tu en penses quoi ?

**Comment by Lyokolux** [comment]
MDR ces expressions :+1:

Question de goût, comme tu le sens

**Comment by johannchopin** [comment]
Alors je modifie 😉 je modifie la branche principale du coup ?

**Comment by Lyokolux** [comment]
oui !

Dans le commit précise au début du message : #1  --> Protip pour fermer l'issue automatiquement
