### ISSUE TITLE
<troll>La fonction show_face en one-liner ?

### ISSUE THREAD

**Issue by Lyokolux** [InfoIsfatesDfhi/Projet_Rubics-cube#2]
Bon voilà, on peut aussi la faire comme ça : 
```python
def show_face(face):
    print('\n'.join([' '.join([face[row*3+col] for col in range(3)]) for row in range(3)]))
```

LA COMPREHENSION DES LISTES C TRO B1.
On perd bien en lisibilité, c'est dégeulasse mais au moins, on n'a pas ce retour à la ligne à la fin ;)
On économise des octets de mémoires en plus :+1: 
\</troll\>

**Comment by johannchopin** [comment]
Mon dieu même un aveugle se tirerai une balle en voyant ça 😆
